# Generated by Django 6.0.6 on 2026-06-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureTag',
            new_name='PropertyType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tags',
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertytype'),
        ),
    ]
